config/routes.rb
LcttPlatform::Application.routes.draw do
  root :to => "home#index"

  # 帐号管理
  resources :users, :only => [:index, :show, :edit, :update]

  # GitHub OAuth
  get '/auth/:provider/callback', to: 'sessions#create',  as: :auth_callback
  get '/signin',                  to: 'sessions#new',     as: :signin
  get '/signout',                 to: 'sessions#destroy', as: :signout
  get '/auth/failure',            to: 'sessions#failure', as: :auth_failure

  # 项目动态
  get '/activity', to: 'activity#index', as: :activity

  # 文章相关
  resources :articles, except: :destroy

  # 管理页面
  get '/management', to: 'management#index', as: :management
end

app/models/article.rb
class Article
  include Mongoid::Document
  # include Mongoid::Versioning FIXME: deprecated
  # include Mongoid::Paranoia   FIXME: deprecated
  include Mongoid::Timestamps

  # 文章所允许的状态
  @valid_states = %i(suggest new translating translated done)
  class << Article
    attr_accessor :valid_states
  end

  # Q: 为什么需要 suggestion？
  # A: 推荐可能摘录自一本书籍之类的，这种情况没有 source_url。
  #    当然，source_url 和 suggestion 有一个不为空就够了。
  # TODO: 将这段注释移动到 validator 部分

  field :title,       type: String # 原文标题（英文）
  field :source,      type: String # 文章来源
  field :source_url,  type: String # 文章来源 URL
  field :license,     type: String # 许可信息（如: 无限制，CC BY-NC-SA 3.0，已经过作者授权，……）
  field :suggestion,  type: String # 推荐稿（英文，任何格式）
  field :original,    type: String # 原文（英文，MarkDown 格式）
  field :translation, type: String # 译文（中文，MarkDown 格式）
  field :publish,     type: String # 终稿（中文，MarkDown 格式）
  field :state,       type: Symbol # 文章状态

  belongs_to :category # 文章分类（默认无分类）
  belongs_to :user     # 所属用户

  validates_presence_of :title, message: '原文标题不能为空'

  # 操作

  def create user
    return false if self.persisted?

    self.user = user
  end

  def claim user
    return false if self.state != :new

    self.user = user
    self.state = :translating
  end

  def submit user, translation
    return false if self.state != :translating

    self.user = user
    self.state = :translated
    self.translation = translation
  end

  def cancel
    return false if self.state != :translating

    self.user = new_owner
    self.state = :new
    self.translation = nil
  end

  def accept user, publish
    return false if self.state != :translated

    self.user = user
    self.state = :done
    self.publish = publish
  end

  def deny
    return false if self.state != :translated

    self.user = new_owner
    self.state = :new
    self.translation = nil
  end

  # 元编程添加直接保存的方法
  %w(create claim submit cancel accept deny).each do |action|
    define_method "#{action}!" do |*args|
      send action, *args
      self.save!
    end
  end

  # FIXME: remove below

  def cancel_translate
    return if self.state != :translating
    self.user = new_owner
    self.state = :new
    self.save!
  end

  # 测试

  def archived?
    !!deleted_at
  end

  # 元编程添加状态检测
  valid_states.each do |state|
    define_method "is_#{state}?" do
      self.state == state
    end
  end

  # 取值

  def all_versions
    a = self.versions.to_a
    a.push self
  end

  def new_owner
    self.all_versions.group_by(&:state)[:new].first.user
  end

  def state_label
    case self.state
    when :suggest     then '新推荐'
    when :new         then '新原文'
    when :translating then '翻译中'
    when :translated  then '已翻译'
    when :done        then '已校对'
    end
  end

  def to_s
    state = state_label
    state = "#{state}-归档" if archived?
    state = "[#{state}]"
    "#{state} #{title}"
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # respond_to :html FIXME: deprecated

  def index
    authorize! :index, Article

    @articles = Article.all

    state = params[:state] and params[:state].to_sym
    @articles = @articles.where state: state if Article.valid_states.include? state
  end

  def new
    @article = Article.new params[:article]

    authorize! :new, @article
  end

  def create
    @article = Article.new params[:article]

    authorize! :create, @article

    @article.create! current_user rescue respond_with @article and return
    flash[:success] = "#{@article.state_label}「#{@article.title}」已创建。"

    respond_with @article
  end

  def edit
    @article = Article.find params[:id]

    authorize! :edit, @article
  end

  def show
    # 同时包括归档的文章
    @article = Article.find params[:id] rescue Article.deleted.find params[:id]

    authorize! :show, @article
  end

  def update
    # 检查 action 然后调用
    action = request.query_parameters[:action]
    actions = %w(approve claim submit cancel accept deny archive restore)
    render status: :not_found and return unless actions.include? action

    @article = Article.find params[:id] rescue Article.deleted.find params[:id]
    send action
  end

  private

  def approve
    # TODO stub
  end

  def claim
    authorize! :claim, @article

    @article.claim! current_user
    flash[:success] = "「#{@article.title}」领取成功。"

    respond_with @article
  end

  def submit
    authorize! :submit, @article

    @article.submit! current_user, params[:article] and params[:article][:translation]
    flash[:success] = "「#{@article.title}」的译文已成功提交。"

    respond_with @article
  end

  def cancel
    authorize! :cancel, @article

    @article.cancel!
    flash[:success] = "你已放弃「#{@article.title}」的翻译。"

    respond_with @article
  end

  def accept
    authorize! :accept, @article

    @article.accept! current_user, params[:article] and params[:article][:publish]
    flash[:success] = "你已完成对「#{@article.title}」的校对。"

    respond_with @article
  end

  def deny
    authorize! :deny, @article

    @article.deny!
    flash[:success] = "你已否决「#{@article.title}」的翻译。"

    respond_with @article
  end

  def archive
    # TODO stub
  end

  def restore
    # TODO stub
  end
end

app/views/articles/_general_info.html.haml
%dt 文章来源
%dd= @article.source

%dt 文章来源 URL
%dd= @article.source_url

%dt 分类
%dd= @article.category

%dt 当前状态
%dd= @article.state_label

%dt 创建时间
%dd= format @article.created_at

%dt 最近修改
%dd
  - if @article.is_new? or @article.is_suggest?
    从未
  - else
    = format @article.updated_at

%dt 许可信息
%dd= @article.license

app/views/articles/edit.html.haml
- @article.original ||= ''

.page-header
  %h3
    管理翻译
    %small= @article.title

.panel.panel-default
  .panel-heading
    .panel-title 相关信息
  .panel-body
    %dl.dl-horizontal
      = render 'general_info'

.panel.panel-default
  .panel-heading
    .panel-title 原文
  .panel-body
    = GitHub::Markdown.render(@article.original).html_safe
  .panel-footer
    = preserve formatter.format(lexer.lex(@article.original)).html_safe

.row
  .col-md-12
    = simple_form_for @article, url: article_path(@article, action: :submit) do |f|
      = f.input :translation, as: :text, label: '译文'
      = f.hidden_field :state, value: 'translated' # 标记为已翻译
      = f.button :submit, '提交选题', class: 'btn btn-success'

/ = link_to '提交翻译', , method: :put, class: "btn btn-success"
= link_to '放弃翻译', article_path(@article, action: :cancel), method: :put, class: "btn btn-danger", data: { confirm: '真的要放弃么？' }

app/views/articles/index.html.haml
.page-header
  %h3 文章列表

= render 'layouts/screen_warning'

%table.table.table-striped.table-hover.table-bordered
  %thead
    %tr
      %th 标题
      %th 分类
      %th 当前状态
      %th.hidden-xs 创建时间
      %th.hidden-xs 最近修改
      %th 长度
      %th

  %tbody
    - @articles.each do |article|
      - # 标记颜色
      - color_class = case article.state
      - when :translating then 'warning'
      - when :translated then 'success'
      - else nil

      %tr{class: color_class}
        %td= article.title
        %td= article.category || '未分类'
        %td= article.state_label
        %td.hidden-xs= format article.created_at
        %td.hidden-xs
          - if article.is_new?
            %strong 从未
          - else
            = format article.updated_at
        %td= article.original && article.original.length || '<strong>空</strong>'.html_safe # FIXME: 添加 before_save 钩子用以缓存
        %td
          = link_to '查看', article_path(article), class: "btn btn-xs btn-block btn-default #{'disabled' unless article.is_new?}"

app/views/articles/new.html.haml
- @article.state = :new
- unless can? :new, @article
  - @article.state = :suggest

.page-header
- if @article.state = :new
  %h3 新建原文
- else
  %h3 新建推荐

= render 'layouts/screen_warning'

.row
  .col-md-12
    = simple_form_for @article do |f|
      = f.input :title, label: '原文标题（英文）'
      = f.input :source, label: '文章来源'
      = f.input :source_url, label: '来源 URL'
      = f.input :license, label: '许可信息'
      = f.input :category, collection: Category.all.group_by(&:ancestor), group_method: :last, as: :grouped_select, label_method: :to_s, value_method: :name, label: '文章分类'
      - if @article.state = :new
        = f.input :original, as: :text, label: '原文内容'
        = f.hidden_field :state, value: 'new'
        = f.button :submit, '提交选题', class: 'btn-default'
      - else
        = f.input :suggestion, as: :text, label: '推荐内容'
        = f.hidden_field :state, value: 'suggest'
        = f.button :submit, '推荐文章', class: 'btn-default'

app/views/articles/proofread_index.html.haml
TODO

app/views/articles/publish_index.html.haml
TODO

app/views/articles/show.html.haml
.page-header
  %h3
    文章翻译进度
    %small= @article.title

.panel.panel-default
  .panel-heading
    .panel-title 相关信息
  .panel-body
    %dl.dl-horizontal
      = render 'general_info'

      - # 参与者信息
      / - versions = @article.versions
      / - versions.push @article

      / - contributors = versions.grouped_by &state

      - if val = @article.new_owner
        %dt 选题
        %dd= val

- if @article.original
  .panel.panel-default
    .panel-heading
      .panel-title 原文
    .panel-body
      = GitHub::Markdown.render(@article.original).html_safe
    .panel-footer
      = preserve formatter.format(lexer.lex(@article.original)).html_safe
- elsif @article.suggestion
  .panel.panel-default
    .panel-heading
      .panel-title 推荐
    .panel-body
      = GitHub::Markdown.render(@article.suggestion).html_safe
    .panel-footer
      = preserve formatter.format(lexer.lex(@article.suggestion)).html_safe

= link_to '认领', article_path(@article, action: :claim), method: :put, class: "btn btn-success #{'disabled' unless @article.is_new?}" if can? :translate, Article

app/views/articles/translate.html.haml
.page-header
  %h3
    管理翻译
    %small= @article.title

.panel.panel-default
  .panel-heading
    .panel-title 相关信息
  .panel-body
    %dl.dl-horizontal
      = render 'general_info'

.panel.panel-default
  .panel-heading
    .panel-title 原文
  .panel-body
    = GitHub::Markdown.render(@article.original).html_safe
  .panel-footer
    = preserve formatter.format(lexer.lex(@article.original)).html_safe

.row
  .col-md-12
    = simple_form_for @article do |f|
      = f.input :translation, as: :text, label: '译文'
      = f.hidden_field :state, value: 'translated' # 标记为已翻译

= link_to '提交翻译', article_path(@article), method: :put, class: "btn btn-success"
= link_to '放弃翻译', translate_article_path(@article), method: :delete, class: "btn btn-danger", data: { confirm: '真的要放弃么？' }

app/views/articles/translate_index.html.haml
.page-header
  %h3 认领原文

= render 'layouts/screen_warning'

%table.table.table-striped.table-hover.table-bordered
  %thead
    %tr
      %th 标题
      %th 分类
      %th 当前状态
      %th.hidden-xs 创建时间
      %th.hidden-xs 最近修改
      %th 长度
      %th

  %tbody
    - @articles.each do |article|
      - # 标记颜色
      - color_class = case article.state
      - when :translating then 'warning'
      - when :translated then 'success'
      - else nil

      %tr{class: color_class}
        %td= article.title
        %td= article.category || '未分类'
        %td= article.state_label
        %td.hidden-xs= format article.created_at
        %td.hidden-xs
          - if article.is_new?
            %strong 从未
          - else
            = format article.updated_at
        %td= article.original.length # FIXME: 添加 before_save 钩子用以缓存
        %td
          = link_to '查看', article_path(article), class: "btn btn-xs btn-block btn-default #{'disabled' unless article.is_new?}"