config/routes.rb
LcttPlatform::Application.routes.draw do
  root :to => "home#index"

  # 帐号管理
  resources :users, :only => [:index, :show, :edit, :update]

  # GitHub OAuth
  get '/auth/:provider/callback', to: 'sessions#create',  as: :auth_callback
  get '/signin',                  to: 'sessions#new',     as: :signin
  get '/signout',                 to: 'sessions#destroy', as: :signout
  get '/auth/failure',            to: 'sessions#failure', as: :auth_failure

  # 项目动态
  get '/activity', to: 'activity#index', as: :activity

  # 文章相关
  resources :articles, except: :destroy

  # 管理页面
  get '/management', to: 'management#index', as: :management
end

app/views/layouts/_footer.html.haml
.container
  %p
    = link_to 'Linux 中国', 'http://linux.cn/'
    %small 翻译小组
    | Powered by
    = link_to 'LCTT-Platform', '//github.com/vizv/LCTT-Platform'
  %p
    %small
      除特别注明外，本站所有翻译内容均为
      = link_to 'CC协议', '//creativecommons.org/licenses/by-nc-sa/3.0/deed.zh'
      授权

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{class: "flash-msg alert alert-#{name.to_s} alert-dismissible", role: 'alert'}
      %button.close{'data-dismiss' => 'alert', :type => 'button'}
        %span{'aria-hidden' => 'true'} &times;
        %span.sr-only Close
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav.navbar.navbar-default.navbar-fixed-top{role: 'navigation'}
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to project_name, root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      = render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.haml
- # 站点导航
%ul.nav.navbar-nav
  - claimed_article = (current_user and current_user.claimed_article)
  %li= link_to '动态', activity_path                      if can? :index, Activity
  %li= link_to '推荐', new_article_path                   if can? :new, Article, state: :suggest
  %li= link_to '添加', new_article_path                   if can? :new, Article, state: :new
  %li= link_to '认领', articles_path(state: :new)         if can? :claim, Article
  %li= link_to '翻译', edit_article_path(claimed_article) if can? :edit, claimed_article
  %li= link_to '校对', articles_path(state: :translated)   if can? :proofread, Article
  %li= link_to '发布', articles_path(state: :done)        if can? :publish, Article
  %li= link_to '管理', management_path                    if can? :manage, :all

- # 用户管理
%ul.nav.navbar-nav.navbar-right
  - if user_signed_in?
    - avatar_tag = image_tag "https://avatars.githubusercontent.com/u/#{current_user.uid}?s=30", class: 'nav-avatar'

    %li= link_to avatar_tag, current_user, style: 'padding: 10px;'
    %li= link_to "#{current_user.name}", current_user

    %li= link_to icon('sign-out') + '登出', signout_path
  - else
    - avatar_tag = image_tag 'not-login.png', class: 'nav-avatar'

    %li= link_to avatar_tag, signin_path, style: 'padding: 10px;'
    %li= link_to '未登录', current_user
    %li= link_to icon('sign-in') + '登陆', signin_path

app/views/layouts/_screen_warning.html.haml
.too-small-show
  .vcenter
    .alert.alert-warning
      %strong 注意：
      屏幕太小无法浏览该页面

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{name: 'viewport',    content: 'width=device-width, initial-scale=1.0'}
    %title= "#{content_for?(:title) && yield(:title) + ' - ' || ''}#{project_name}"
    %meta{name: 'description', content: "#{content_for?(:description) ? yield(:description) : project_name}"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    %main.container{role: 'main'}
      = render 'layouts/messages'
      = yield
    %footer
      = render 'layouts/footer'